#
#	Makefile -- Build instructions for Conexant/P52
#

ROMFSIMG = $(IMAGEDIR)/romfs.img
IMAGE    = $(IMAGEDIR)/image.bin
ROMFS_BUILT = busybox dnrd init iptables nicdbg noip2 pppd romedebug sh upnp w x

ROMFS_DIRS = bin dev etc home lib mnt proc usr var www etc/config

DEVICES = \
	tty,c,5,0      console,c,5,1      cua0,c,5,64      cua1,c,5,65  \
	\
	mem,c,1,1      kmem,c,1,2         null,c,1,3       ram0,b,1,0 \
	ram1,b,1,1 \
	\
	ppp,c,108,0 \
	ptyp0,c,2,0    ptyp1,c,2,1        ptyp2,c,2,2      ptyp3,c,2,3 \
	ptyp4,c,2,4    ptyp5,c,2,5        ptyp6,c,2,6      ptyp7,c,2,7 \
	ptyp8,c,2,8    ptyp9,c,2,9        ptypa,c,2,10     ptypb,c,2,11 \
	ptypc,c,2,12   ptypd,c,2,13       ptype,c,2,14     ptypf,c,2,15 \
	\
	rom0,b,31,0    rom1,b,31,1        rom2,b,31,2      rom3,b,31,3 \
	rom4,b,31,4    rom5,b,31,5        rom6,b,31,6      rom7,b,31,7 \
	rom8,b,31,8    rom9,b,31,9 \
	\
	tty0,c,4,0     tty1,c,4,1         tty2,c,4,2       tty3,c,4,3 \
	tty4,c,4,4    tty5,c,4,5\
	ttyS0,c,4,64   ttyS1,c,4,65 \
	\
	ttyp0,c,3,0    ttyp1,c,3,1        ttyp2,c,3,2      ttyp3,c,3,3 \
	ttyp4,c,3,4    ttyp5,c,3,5        ttyp6,c,3,6      ttyp7,c,3,7 \
	ttyp8,c,3,8    ttyp9,c,3,9        ttypa,c,3,10     ttypb,c,3,11 \
	ttypc,c,3,12   ttypd,c,3,13       ttype,c,3,14     ttypf,c,3,15 \
	\
	zero,c,1,5     random,c,1,8       urandom,c,1,9 


clean:

romfs:
	[ -d $(ROMFSDIR)/$$i ] || mkdir -p $(ROMFSDIR)
	for i in $(ROMFS_DIRS); do \
		[ -d $(ROMFSDIR)/$$i ] || mkdir -p $(ROMFSDIR)/$$i; \
	done
	for i in $(DEVICES); do \
		touch $(ROMFSDIR)/dev/@$$i; \
	done
	$(ROMFSINST) -s var/tmp /tmp
	$(ROMFSINST) -s bin /sbin
	$(ROMFSINST) /etc/rc
	$(ROMFSINST) /etc/hosts
	$(ROMFSINST) -s /var/resolv.conf /etc/resolv.conf
	$(ROMFSINST) /etc/inittab
	$(ROMFSINST) ../../Generic/romfs/etc/services /etc/services
	case "$(LINUXDIR)" in \
	*2.4.*) ;; \
	*) echo "ttyS0:linux:/bin/sh" >> $(ROMFSDIR)/etc/inittab ;; \
	esac
	$(ROMFSINST) /etc/udhcpd.conf
	$(ROMFSINST) /etc/ppp.options
	$(ROMFSINST) -s /bin/webs /bin/ip-up
	$(ROMFSINST) -s /bin/webs /bin/ip-down

	#$(ROMFSINST) -s /bin/busybox /bin/ls
	#$(ROMFSINST) -s /bin/busybox /bin/cat
	#$(ROMFSINST) -s /bin/busybox /bin/mount
	#$(ROMFSINST) -s /bin/busybox /bin/mkdir
	$(ROMFSINST) -s /bin/busybox /bin/route
	#$(ROMFSINST) -s /bin/busybox /bin/tftp
	#$(ROMFSINST) -s /bin/busybox /bin/reboot
	#$(ROMFSINST) -s /bin/busybox /bin/uptime
	#$(ROMFSINST) -s /bin/busybox /bin/echo
	$(ROMFSINST) -s /bin/busybox /bin/syslogd
	$(ROMFSINST) -s /bin/busybox /bin/rdate
	$(ROMFSINST) -s /var/syslog /dev/log
	$(ROMFSINST) -s /var/log/messages /www/system.log
	#$(ROMFSINST) /etc/passwd
	#$(ROMFSINST) /etc/termcap
	#$(ROMFSINST) /etc/config/boa.conf
	echo "$(VERSIONSTR) -- " `date` > $(ROMFSDIR)/etc/version
	for i in $(ROMFS_BUILT); do \
		$(ROMFSINST) /bin/$$i; \
	done
	$(ROMFSINST) -s  /bin/busybox /bin/udhcpc
	$(ROMFSINST) -s  /bin/busybox /bin/udhcpd
	$(ROMFSINST) -s  /bin/busybox /bin/ping
	$(ROMFSINST) -s  /bin/busybox /bin/ifconfig
	$(ROMFSINST) -s /bin/nicdbg /bin/dpppoe
	$(ROMFSINST) -s /bin/nicdbg /bin/dvlan
	$(ROMFSINST) -s /bin/nicdbg /bin/dl3
	$(ROMFSINST) -s /bin/nicdbg /bin/dtcp
	$(ROMFSINST) -s /bin/nicdbg /bin/dicmp
	$(ROMFSINST) -s /bin/nicdbg /bin/dalg
	$(ROMFSINST) -s /bin/nicdbg /bin/dip
	$(ROMFSINST) -s /bin/nicdbg /bin/dpvid
	$(ROMFSINST) -s /bin/nicdbg /bin/dtrap
	$(ROMFSINST) -s /bin/nicdbg /bin/darp
	$(ROMFSINST) -s /bin/nicdbg /bin/dsp
	$(ROMFSINST) -s /bin/nicdbg /bin/dacl
	$(ROMFSINST) -s /bin/romedebug /bin/xpppoe
	#$(ROMFSINST) upnp/sample/pseudoicsd/pseudoicsd /bin/upnp
	$(ROMFSINST) ../user/libupnp-1.2.1/upnp/sample/pseudoicsd/web /etc/pseudoicsd
	$(ROMFSINST) -s /var/run/picsdecs.xml /etc/pseudoicsd/picsdesc.xml
			
image:
	[ -d $(IMAGEDIR) ] || mkdir -p $(IMAGEDIR)
	../tools/genromfs -v -V "ROMdisk" -f $(ROMFSIMG) -d $(ROMFSDIR)
	mips-uclibc-ld -EB -Tld.script.rd -b binary -o $(IMAGEDIR)/rom_image $(ROMFSIMG)
