#
# libposix makefile
# $Id: Makefile,v 1.1.1.1 2003/08/27 06:20:20 rupert Exp $
#

ARCHFLAGS = 

SRCS = libposix.c
OBJS = libposix.o

CFLAGS = -O -D_POSIX_SOURCE $(ARCHFLAGS)

all: $(OBJS)

clean:
	rm -f *.o *~ core

