#	$Id: Makefile.bsd,v 1.1.1.1 2003/08/27 06:20:20 rupert Exp $

PROG=	pppstats
SRCS=	pppstats.c
CFLAGS+=-I../include -D_BITYPES
MAN8=	pppstats.8
MAN=	pppstats.cat8
BINDIR=	/usr/sbin

.include <bsd.prog.mk>
