#
# Makefile for Inprocomm 2220AP device drivers.
#

O_TARGET	:= IPN2220AP.o

obj-y 	= IPN2220 wlan_kal.o wlan_os.o wds_os.o ap_wext.o netdev_1x.o
obj-m   := $(O_TARGET)

include $(TOPDIR)/Rules.make
